# Generated by Django 5.0 on 2024-06-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_article_image_url_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogreview",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="base.article",
            ),
            preserve_default=False,
        ),
    ]
