# Generated by Django 5.0 on 2024-06-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_visitor_remove_blogreview_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitor",
        ),
        migrations.AddField(
            model_name="blogreview",
            name="subject",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
